/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * User API
 * API for managing users
 * OpenAPI spec version: 1.0.0
 */

export interface User {
  id: number;
  name: string;
  email: string;
}
